pluginManagement {

    repositories {
        maven { url 'https://maven.aliyun.com/repository/public' }
        mavenCentral()
        gradlePluginPortal()
        maven { url 'https://jitpack.io' }
        google()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url "https://maven.aliyun.com/repository/public" }
        mavenCentral()
        maven { url 'https://jitpack.io' }
        google()
    }

}

rootProject.name = "FreezeApp"

include ':app'
include ':hidden-api-stub'
project(':hidden-api-stub').projectDir = new File(rootDir, 'hidden-api/hidden-api-stub')
include ':hidden-api-processor'
project(':hidden-api-processor').projectDir = new File(rootDir, 'hidden-api/hidden-api-processor')
include ':hidden-api-annotation'
project(':hidden-api-annotation').projectDir = new File(rootDir, 'hidden-api/hidden-api-annotation')
includeBuild 'hidden-api/hidden-api-plugin'
include ':daemon'
include ':common'
include ':adb'
include ':reflect'
