plugins {
    id("com.android.application")
    id 'replace-plugin'
}

android {
    namespace 'com.john.freezeapp'
    compileSdk rootProject.ext.COMPILE_SDK_VERSION

    defaultConfig {
        applicationId "com.john.freezeapp"
        minSdk rootProject.ext.MIN_SDK_VERSION
        targetSdk 33
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "arm64-v8a"
        }
        buildConfigField 'String', 'DAEMON_CLASS_NAME', '\"com.john.freezeapp.daemon.Daemon\"'
        buildConfigField 'long', 'FREEZEAPP_VERSION', "${System.currentTimeMillis()}"
    }

    signingConfigs {
        sky {
            storeFile file("${rootDir}/keyStore/demo.jks")
            storePassword 'song123'
            keyAlias 'demo'
            keyPassword 'song123'
        }
        debug {
            storeFile file("/Users/juneleo/amap/amap_nextci/android/Test.keystore")
            storePassword '123456'
            keyAlias 'test'
            keyPassword '123456'
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.sky
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }



    buildFeatures {
        buildConfig true
        prefab true
    }

    lintOptions {
        checkReleaseBuilds false
        // 或者禁用所有警告
        checkAllWarnings false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.gson
    implementation libs.recyclerview
    implementation libs.material
    debugImplementation libs.shisuku.api
    debugImplementation libs.shisuku.provider
    implementation libs.hiddenapibypass
    implementation libs.wheelpicker
    implementation libs.cxx
    annotationProcessor project(':hidden-api-processor')
    compileOnly project(':hidden-api-stub')
    implementation project(':hidden-api-annotation')
    implementation project(':common')
    implementation project(':daemon')
    implementation project(':adb')
    implementation project(':reflect')
    implementation 'top.canyie.pine:core:0.3.0'
}

android.applicationVariants.all { variant ->
    def variantName = variant.name.capitalize()
    def mergeAssetsTask = tasks.named("merge${variantName}Assets").get()
    def compressAssetsTask = tasks.named("compress${variantName}Assets").get()


//    // 创建复制 daemon.apk 的任务
//    task("copyDaemonApk${variantName}", type: Copy) {
//        from new File(project(':daemon').buildDir, "outputs/apk/debug/daemon-debug.apk")
//        into mergeAssetsTask.outputs.files.singleFile
//        rename { String fileName -> 'daemon.apk' }
//
//        // 关闭增量构建
//        outputs.upToDateWhen { false }
//    }
//    def copyDaemonApkTask = tasks.named("copyDaemonApk${variantName}").get()
//    compressAssetsTask.dependsOn copyDaemonApkTask
//    copyDaemonApkTask.dependsOn mergeAssetsTask
}