plugins {
    alias(libs.plugins.android.library)
    id 'replace-plugin'
}

version = '1.0'

android {
    namespace 'com.john.freezeapp.daemon'
    compileSdk rootProject.ext.COMPILE_SDK_VERSION

    defaultConfig {
        minSdk rootProject.ext.MIN_SDK_VERSION
        consumerProguardFiles "consumer-rules.pro"
        buildConfigField 'String', 'DAEMON_VERSION', "\"${version}\""
        buildConfigField 'String', 'CLIENT_PACKAGE', '\"com.john.freezeapp\"'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        buildConfig true
        prefab true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}


/**
 *  <!-- Retrofit for HTTP client -->
 <dependency>
 <groupId>com.squareup.retrofit2</groupId>
 <artifactId>retrofit</artifactId>
 <version>2.9.0</version>
 </dependency>

 <!-- RxJava2 for Retrofit -->
 <dependency>
 <groupId>com.squareup.retrofit2</groupId>
 <artifactId>adapter-rxjava2</artifactId>
 <version>2.9.0</version>
 </dependency>

 <!-- Jackson for JSON -->
 <dependency>
 <groupId>com.squareup.retrofit2</groupId>
 <artifactId>converter-jackson</artifactId>
 <version>2.9.0</version>
 </dependency>

 <!-- Jackson core (explicit dependency) -->
 <dependency>
 <groupId>com.fasterxml.jackson.core</groupId>
 <artifactId>jackson-databind</artifactId>
 <version>2.15.2</version>
 </dependency>

 <!-- OkHttp (required by Retrofit) -->
 <dependency>
 <groupId>com.squareup.okhttp3</groupId>
 <artifactId>okhttp</artifactId>
 <version>4.12.0</version>
 </dependency>

 implementation 'com.theokanning.openai-gpt3-java:service:0.18.2'
 */

dependencies {
    implementation libs.gson
    implementation libs.annotation
    implementation libs.appcompat
    implementation libs.nanohttpd
    annotationProcessor project(':hidden-api-processor')
    compileOnly project(':hidden-api-stub')
    implementation project(':hidden-api-annotation')
    implementation project(':common')
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.9.0'
    implementation 'com.squareup.retrofit2:converter-jackson:2.9.0'
}
